hostname = sns.umetrip.com, appmsg.umetrip.com, umehome.umetrip.com, opactivity.umetrip.com, activity.umetrip.com, umerp.umetrip.com, umeflightstatus.umetrip.com, umestartup.umetrip.com

https:\/\/(?:sns|appmsg|umehome|opactivity|activity|umerp|umeflightstatus|umestartup)\.umetrip\.com\/gateway\/api\/umetrip\/native$ url script-response-body https://raw.githubusercontent.com/SIMPO18/Script/refs/heads/main/umetrip.js
